import { useEffect, useState } from 'react';
import {
  Activity, ArrowUpRight, BarChart3, Bell, Bot, BriefcaseBusiness, ChevronDown,
  CircleDollarSign, Database, Gauge, Globe2, Inbox, LayoutDashboard,
  Menu, MessageSquare, MoreHorizontal, Plus, Search, Settings2, ShieldCheck,
  Languages, Moon, Smartphone, Sparkles, Sun, Target, Users, X,
} from 'lucide-react';
import WorkspaceModule from './WorkspaceModule';

type Lead = { initials: string; name: string; company: string; service: string; value: string; stage: string; tone: string };

const leads: Lead[] = [
  { initials: 'MR', name: 'Mariana Rojas', company: 'Northstar Health', service: 'AI automation', value: '$18k–$25k', stage: 'Qualified', tone: 'coral' },
  { initials: 'DL', name: 'Daniel López', company: 'Lumen Foods', service: 'Mobile product', value: '$12k–$18k', stage: 'Discovery', tone: 'aqua' },
  { initials: 'SA', name: 'Sofia Alvarez', company: 'Independent', service: 'Web platform', value: '$8k–$12k', stage: 'New inquiry', tone: 'violet' },
  { initials: 'JT', name: 'James Turner', company: 'Redwood Labs', service: 'Custom software', value: '$25k+', stage: 'Proposal', tone: 'lime' },
];

const nav = [
  { label: 'Overview', icon: LayoutDashboard }, { label: 'Leads & pipeline', icon: Inbox, badge: '12' },
  { label: 'Companies', icon: BriefcaseBusiness }, { label: 'Campaigns', icon: Target },
  { label: 'Analytics', icon: BarChart3 }, { label: 'Conversations', icon: MessageSquare },
  { label: 'Account registry', icon: Database },
];

const products = ['All products', 'ClubGamerZone website', 'Organify', 'CV Enhancer', 'Games portfolio'];
const productStats: Record<string, { opportunities: string; pipeline: string; qualified: string; cpl: string }> = {
  'All products': { opportunities: '24', pipeline: '$184.6k', qualified: '42.8%', cpl: '$64.20' },
  'ClubGamerZone website': { opportunities: '12', pipeline: '$96.4k', qualified: '46.1%', cpl: '$58.40' },
  Organify: { opportunities: '4', pipeline: '$28.8k', qualified: '35.0%', cpl: '$71.80' },
  'CV Enhancer': { opportunities: '5', pipeline: '$42.5k', qualified: '44.7%', cpl: '$62.10' },
  'Games portfolio': { opportunities: '3', pipeline: '$16.9k', qualified: '31.6%', cpl: '$83.60' },
};

function App() {
  const [active, setActive] = useState('Overview');
  const [sidebarOpen, setSidebarOpen] = useState(false);
  const [range, setRange] = useState('Last 30 days');
  const [product, setProduct] = useState('All products');
  const [searchOpen, setSearchOpen] = useState(false);
  const [leadFormSignal, setLeadFormSignal] = useState(0);
  const [language, setLanguage] = useState<'en' | 'es'>(() => localStorage.getItem('signaldesk-language') === 'es' ? 'es' : 'en');
  const [theme, setTheme] = useState<'light' | 'dark'>(() => localStorage.getItem('signaldesk-theme') === 'dark' ? 'dark' : 'light');
  const stats = productStats[product];
  const es = language === 'es';
  const text = (en: string, spanish: string) => es ? spanish : en;
  const navLabels: Record<string, string> = { Overview: text('Overview', 'Resumen'), 'Leads & pipeline': text('Leads & pipeline', 'Prospectos y embudo'), Companies: text('Companies', 'Empresas'), Campaigns: text('Campaigns', 'Campañas'), Analytics: text('Analytics', 'Analítica'), Conversations: text('Conversations', 'Conversaciones'), 'Account registry': text('Account registry', 'Registro de cuentas') };
  const productLabels: Record<string, string> = { 'All products': text('All products', 'Todos los productos'), 'ClubGamerZone website': text('ClubGamerZone website', 'Sitio ClubGamerZone'), Organify: 'Organify', 'CV Enhancer': text('CV Enhancer', 'Optimizador de CV'), 'Games portfolio': text('Games portfolio', 'Portafolio de juegos') };

  useEffect(() => { document.documentElement.dataset.theme = theme; localStorage.setItem('signaldesk-theme', theme); }, [theme]);
  useEffect(() => { document.documentElement.lang = language; localStorage.setItem('signaldesk-language', language); }, [language]);

  return <div className="app-shell">
    <aside className={`sidebar ${sidebarOpen ? 'sidebar-open' : ''}`}>
      <div className="brand"><span className="brand-mark"><Sparkles size={16} /></span><span>signal<span className="brand-accent">desk</span></span></div>
      <div className="workspace-switcher"><span className="workspace-avatar">C</span><span><small>{text('Workspace', 'Espacio')}</small><strong>ClubGamerZone</strong></span><ChevronDown size={15} /></div>
      <nav className="main-nav" aria-label={text('Main navigation', 'Navegación principal')}>{nav.map(item => <button key={item.label} className={active === item.label ? 'nav-item active' : 'nav-item'} onClick={() => { setActive(item.label); setSidebarOpen(false); }}><item.icon size={17} /><span>{navLabels[item.label]}</span>{item.badge && <em>{item.badge}</em>}</button>)}</nav>
      <div className="sidebar-bottom"><div className="health-card"><span className="pulse-dot" /><div><strong>{text('Demo workspace ready', 'Espacio demo listo')}</strong><small>{text('Connections pending setup', 'Conexiones pendientes')}</small></div></div><button className="nav-item"><Settings2 size={17} /><span>{text('Settings', 'Configuración')}</span></button><div className="user-row"><span className="user-avatar">JD</span><span><strong>Jose Demoya</strong><small>{text('Administrator', 'Administrador')}</small></span><MoreHorizontal size={16} /></div></div>
    </aside>
    {sidebarOpen && <button className="scrim" aria-label="Close navigation" onClick={() => setSidebarOpen(false)} />}
    <main className="main-content">
      <header className="topbar"><button className="mobile-menu" onClick={() => setSidebarOpen(true)} aria-label={text('Open navigation', 'Abrir navegación')}><Menu size={20} /></button><div className="breadcrumbs"><span>{text('Workspace', 'Espacio')}</span><span>/</span><strong>{navLabels[active]}</strong></div><div className="top-actions"><button className="preference-button" onClick={() => setLanguage(es ? 'en' : 'es')} aria-label={text('Switch to Spanish', 'Cambiar a inglés')}><Languages size={14} /><span>{es ? '🇨🇴 ES' : '🇺🇸 EN'}</span></button><button className="icon-button theme-toggle" onClick={() => setTheme(theme === 'light' ? 'dark' : 'light')} aria-label={text('Toggle dark mode', 'Cambiar modo oscuro')}>{theme === 'light' ? <Moon size={17} /> : <Sun size={17} />}</button>{searchOpen ? <div className="search-field"><Search size={15} /><input autoFocus placeholder={text('Search leads, companies...', 'Buscar prospectos, empresas...')} onBlur={() => setSearchOpen(false)} /></div> : <button className="icon-button" aria-label={text('Search', 'Buscar')} onClick={() => setSearchOpen(true)}><Search size={18} /></button>}<button className="icon-button notification" aria-label={text('Notifications', 'Notificaciones')}><Bell size={18} /><i /></button><button className="top-avatar">JD</button></div></header>
      <div className="page-wrap">
        <section className="page-heading"><div><p className="eyebrow"><span /> {text('Monday, September 1, 2026', 'Lunes, 1 de septiembre de 2026')}</p><h1>{active === 'Overview' ? <>{text('Good morning, Jose', 'Buenos días, Jose')}<span>.</span></> : <>{navLabels[active]}<span>.</span></>}</h1><p className="subheading">{active === 'Overview' ? text('Here’s the pulse of your growth engine.', 'Este es el pulso de tu motor de crecimiento.') : text('ClubGamerZone growth workspace.', 'Espacio de crecimiento de ClubGamerZone.')}</p></div><div className="heading-actions"><label className="scope-select"><small>{text('Reporting scope', 'Alcance')}</small><select value={product} onChange={event => setProduct(event.target.value)} aria-label={text('Reporting scope', 'Alcance del reporte')}>{products.map(item => <option key={item} value={item}>{productLabels[item]}</option>)}</select></label><label className="scope-select"><small>{text('Date range', 'Período')}</small><select value={range} onChange={event => setRange(event.target.value)} aria-label={text('Date range', 'Período')}><option value="Last 7 days">{text('Last 7 days', 'Últimos 7 días')}</option><option value="Last 30 days">{text('Last 30 days', 'Últimos 30 días')}</option><option value="This quarter">{text('This quarter', 'Este trimestre')}</option><option value="This year">{text('This year', 'Este año')}</option></select></label><button className="button button-primary" onClick={() => { setActive('Leads & pipeline'); setLeadFormSignal(value => value + 1); }}><Plus size={16} /> {text('Add lead', 'Añadir prospecto')}</button></div></section>
        <div className="demo-banner"><span className="demo-pulse" /><div><strong>{text('Demo workspace', 'Espacio de demostración')}</strong><span>{productLabels[product]} · {text('Connect your data sources to replace these representative values with live performance.', 'Conecta tus fuentes de datos para reemplazar estos valores representativos con rendimiento real.')}</span></div><button onClick={() => setActive('Account registry')}>{text('Review connections', 'Revisar conexiones')} <ArrowUpRight size={14} /></button></div>
        {active !== 'Overview' ? <WorkspaceModule active={active} product={productLabels[product]} language={language} openLeadFormSignal={leadFormSignal} /> : <>
        <section className="metric-grid"><Metric icon={Users} label={text('Open opportunities', 'Oportunidades abiertas')} value={stats.opportunities} change="+18.4%" note={text('vs. previous period', 'vs. período anterior')} tone="aqua" /><Metric icon={CircleDollarSign} label={text('Pipeline value', 'Valor del embudo')} value={stats.pipeline} change="+12.8%" note={text('weighted: $92.3k', 'ponderado: $92.3k')} tone="lime" /><Metric icon={Gauge} label={text('Qualified rate', 'Tasa de calificación')} value={stats.qualified} change="+6.2%" note={text('of new inquiries', 'de nuevas consultas')} tone="violet" /><Metric icon={ArrowUpRight} label={text('Cost per qualified lead', 'Costo por prospecto calificado')} value={stats.cpl} change="−14.5%" note={text('across paid channels', 'en canales pagos')} tone="coral" /></section>
        <section className="dashboard-grid"><div className="panel funnel-panel"><PanelHeader title={text('Funnel performance', 'Rendimiento del embudo')} detail={text('Conversion journey', 'Ruta de conversión')} action={text('View report', 'Ver informe')} /><div className="funnel-chart"><div className="chart-axis"><span>200</span><span>150</span><span>100</span><span>50</span><span>0</span></div><div className="bars">{[[text('Visits','Visitas'),'184',72,'aqua'],[text('Engaged','Interesados'),'112',55,'aqua'],[text('Inquiries','Consultas'),'48',35,'lime'],[text('Qualified','Calificados'),'24',22,'lime'],[text('Won','Ganados'),'7',12,'coral']].map(([label,val,height,tone]) => <div className="bar-column" key={label as string}><div className={`bar bar-${tone}`} style={{height: `${height}%`}}><span>{val}</span></div><small>{label}</small></div>)}</div></div><div className="chart-foot"><span><i className="legend-dot aqua" /> {text('This period', 'Este período')}</span><span><i className="legend-dot muted" /> {text('Previous period', 'Período anterior')}</span><strong>+22.4% <small>{text('overall conversion', 'conversión total')}</small></strong></div></div><div className="panel activity-panel"><PanelHeader title={text('Live activity', 'Actividad reciente')} detail={text('Last 24 hours', 'Últimas 24 horas')} action={text('See all', 'Ver todo')} /><div className="activity-list"><ActivityRow icon={MessageSquare} title={text('New AI conversation', 'Nueva conversación con IA')} desc={text('Project quotation · Web platform', 'Cotización · Plataforma web')} time={text('8m ago', 'hace 8m')} tone="aqua" /><ActivityRow icon={Globe2} title={text('Organic visit', 'Visita orgánica')} desc="/services/ai-integration" time={text('24m ago', 'hace 24m')} tone="lime" /><ActivityRow icon={Users} title={text('Lead qualified', 'Prospecto calificado')} desc="Mariana Rojas · Northstar Health" time={text('1h ago', 'hace 1h')} tone="violet" /><ActivityRow icon={Target} title={text('Campaign milestone', 'Hito de campaña')} desc={text('AI Automation · 100 clicks', 'Automatización IA · 100 clics')} time={text('2h ago', 'hace 2h')} tone="coral" /></div><button className="text-button">{text('Open activity stream', 'Abrir actividad')} <ArrowUpRight size={14} /></button></div></section>
        <section className="dashboard-grid bottom-grid"><div className="panel pipeline-panel"><PanelHeader title={text('Pipeline', 'Embudo')} detail={text('4 active stages', '4 etapas activas')} action={text('Open CRM', 'Abrir CRM')} /><div className="pipeline-columns">{['New inquiry','Qualified','Proposal','Won'].map((stage, idx) => <div className="pipeline-column" key={stage}><div className="column-head"><span>{({ 'New inquiry': text('New inquiry','Nueva consulta'), Qualified: text('Qualified','Calificado'), Proposal: text('Proposal','Propuesta'), Won: text('Won','Ganado') } as Record<string,string>)[stage]}</span><b>{idx === 0 ? '12' : idx === 1 ? '6' : idx === 2 ? '4' : '2'}</b></div>{leads.filter(l => l.stage === stage || (idx === 1 && l.stage === 'Discovery')).slice(0, 2).map(lead => <LeadCard key={lead.name} lead={lead} />)}</div>)}</div></div><div className="panel integrations-panel"><PanelHeader title={text('Account registry', 'Registro de cuentas')} detail={text('Connection readiness', 'Estado de conexión')} action={text('Manage', 'Gestionar')} /><div className="integration-list"><Integration icon={BarChart3} name="Google Analytics 4" detail="clubgamerzone.com" status={text('Not connected', 'Sin conectar')} tone="aqua" /><Integration icon={CircleDollarSign} name="Google Ads" detail={text('Lead acquisition', 'Adquisición de prospectos')} status={text('Not connected', 'Sin conectar')} tone="violet" /><Integration icon={Smartphone} name="Google AdMob" detail={text('Apps & games revenue', 'Ingresos de apps y juegos')} status={text('Not connected', 'Sin conectar')} tone="lime" /><Integration icon={Target} name="Meta Business" detail="ClubGamerZone" status={text('Not connected', 'Sin conectar')} tone="coral" /><Integration icon={Bot} name={text('AI assistant', 'Asistente de IA')} detail="Netlify Function" status={text('Endpoint pending', 'Endpoint pendiente')} tone="aqua" /><Integration icon={Globe2} name="Netlify" detail="clubgamerzone-webapp" status={text('Needs token', 'Requiere token')} tone="coral" /></div><button className="registry-link" onClick={() => setActive('Account registry')}>{text('View all connections', 'Ver todas las conexiones')} <ArrowUpRight size={14} /></button></div></section>
        </>}
        <footer className="page-footer"><span><ShieldCheck size={14} /> {text('Private workspace · Data stays under your control', 'Espacio privado · Tus datos permanecen bajo tu control')}</span><span>SignalDesk v0.1 · <a href="https://github.com/clubgamerzone" target="_blank" rel="noreferrer">ClubGamerZone</a></span></footer>
      </div>
    </main>
  </div>;
}

function Metric({ icon: Icon, label, value, change, note, tone }: { icon: typeof Users; label: string; value: string; change: string; note: string; tone: string }) { return <article className="metric-card"><div className={`metric-icon icon-${tone}`}><Icon size={18} /></div><div className="metric-label">{label}</div><strong className="metric-value">{value}</strong><div className="metric-change"><span className={change.startsWith('−') ? 'negative' : ''}>{change}</span> {note}</div></article>; }
function PanelHeader({ title, detail, action }: { title: string; detail: string; action: string }) { return <div className="panel-header"><div><h2>{title}</h2><span>{detail}</span></div><button className="panel-action">{action} <ArrowUpRight size={13} /></button></div>; }
function ActivityRow({ icon: Icon, title, desc, time, tone }: { icon: typeof Activity; title: string; desc: string; time: string; tone: string }) { return <div className="activity-row"><span className={`activity-icon icon-${tone}`}><Icon size={15} /></span><div><strong>{title}</strong><small>{desc}</small></div><time>{time}</time></div>; }
function LeadCard({ lead }: { lead: Lead }) { return <div className="lead-card"><div className="lead-top"><span className={`lead-avatar avatar-${lead.tone}`}>{lead.initials}</span><button aria-label={`More actions for ${lead.name}`}><MoreHorizontal size={14} /></button></div><strong>{lead.name}</strong><small>{lead.company}</small><div className="lead-meta"><span>{lead.service}</span><b>{lead.value}</b></div></div>; }
function Integration({ icon: Icon, name, detail, status, tone }: { icon: typeof BarChart3; name: string; detail: string; status: string; tone: string }) { return <div className="integration-row"><span className={`integration-icon icon-${tone}`}><Icon size={15} /></span><div><strong>{name}</strong><small>{detail}</small></div><span className="integration-status"><i className={`status-dot dot-${tone}`} />{status}</span></div>; }

export default App;
