import { ArrowUpRight, BarChart3, Bot, CircleDollarSign, Database, Globe2, Inbox, LoaderCircle, MessageSquare, RefreshCw, Smartphone, Target, Users } from 'lucide-react';
import { useMemo } from 'react';
import { type OverviewLead, useWorkspaceOverview } from './hooks/useWorkspaceOverview';
import type { LeadStage } from './hooks/useWorkspaceLeads';

type Props = { product: string; range: string; language: 'en' | 'es'; onNavigate: (module: string) => void };

const demoRecords: OverviewLead[] = [
  { id: 'demo-1', name: 'Mariana Rojas', company: 'Northstar Health', service: 'AI automation', stage: 'qualified', source: 'AI assistant', estimated_value_min: 18000, estimated_value_max: 25000, created_at: new Date().toISOString() },
  { id: 'demo-2', name: 'Daniel López', company: 'Lumen Foods', service: 'Mobile product', stage: 'discovery', source: 'Referral', estimated_value_min: 12000, estimated_value_max: 18000, created_at: new Date().toISOString() },
  { id: 'demo-3', name: 'Sofia Alvarez', company: 'Independent', service: 'Web platform', stage: 'new_inquiry', source: 'Website form', estimated_value_min: 8000, estimated_value_max: 12000, created_at: new Date().toISOString() },
  { id: 'demo-4', name: 'James Turner', company: 'Redwood Labs', service: 'Custom software', stage: 'proposal', source: 'LinkedIn', estimated_value_min: 25000, estimated_value_max: null, created_at: new Date().toISOString() },
];

const stageOrder: LeadStage[] = ['new_inquiry', 'discovery', 'qualified', 'proposal', 'won'];
const tones = ['aqua', 'violet', 'lime', 'coral'];

export default function OverviewDashboard({ product, range, language, onNavigate }: Props) {
  const es = language === 'es';
  const text = (en: string, spanish: string) => es ? spanish : en;
  const { records: liveRecords, mode, error, reload } = useWorkspaceOverview(product, range);
  const records = mode === 'demo' ? demoRecords : liveRecords;
  const stageLabel = (stage: LeadStage) => ({ new_inquiry: text('New', 'Nuevos'), discovery: text('Discovery', 'Descubrimiento'), qualified: text('Qualified', 'Calificados'), proposal: text('Proposal', 'Propuesta'), won: text('Won', 'Ganados'), lost: text('Lost', 'Perdidos') })[stage];
  const rangeLabel = ({ 'Last 7 days': text('Last 7 days', 'Últimos 7 días'), 'Last 30 days': text('Last 30 days', 'Últimos 30 días'), 'This quarter': text('This quarter', 'Este trimestre'), 'This year': text('This year', 'Este año') } as Record<string, string>)[range] ?? range;

  const summary = useMemo(() => {
    const open = records.filter(item => !['won', 'lost'].includes(item.stage));
    const pipeline = open.reduce((total, item) => total + (item.estimated_value_min !== null && item.estimated_value_max !== null ? (item.estimated_value_min + item.estimated_value_max) / 2 : item.estimated_value_min ?? item.estimated_value_max ?? 0), 0);
    const advanced = records.filter(item => ['qualified', 'proposal', 'won'].includes(item.stage)).length;
    const stageCounts = Object.fromEntries(stageOrder.map(stage => [stage, records.filter(item => item.stage === stage).length])) as Record<LeadStage, number>;
    return { open, pipeline, qualifiedRate: records.length ? advanced / records.length * 100 : 0, stageCounts };
  }, [records]);

  const money = new Intl.NumberFormat(es ? 'es-CO' : 'en-US', { style: 'currency', currency: 'USD', maximumFractionDigits: 1, notation: 'compact' }).format(summary.pipeline);
  const chartMax = Math.max(0, ...stageOrder.map(stage => summary.stageCounts[stage]));

  return <>
    <div className={`demo-banner overview-source source-${mode}`}><span className={mode === 'live' ? 'pulse-dot' : 'demo-pulse'} />
      <div><strong>{mode === 'live' ? text('Live CRM overview', 'Resumen CRM conectado') : mode === 'loading' ? text('Loading CRM overview…', 'Cargando resumen CRM…') : mode === 'error' ? text('CRM overview unavailable', 'Resumen CRM no disponible') : text('Representative CRM preview', 'Vista previa representativa')}</strong><span>{mode === 'live' ? text('Lead, pipeline and funnel values come from Supabase. Advertising and traffic require their connectors.', 'Los prospectos, el embudo y sus valores vienen de Supabase. La publicidad y el tráfico requieren sus conexiones.') : mode === 'error' ? error : text('Sign in with Supabase to replace these records with live data.', 'Inicia sesión con Supabase para reemplazar estos registros con datos reales.')}</span></div>
      {mode === 'error' ? <button onClick={() => void reload()}><RefreshCw size={14} /> {text('Retry', 'Reintentar')}</button> : <button onClick={() => onNavigate('Account registry')}>{text('Review connections', 'Revisar conexiones')} <ArrowUpRight size={14} /></button>}
    </div>
    <section className="metric-grid"><Metric label={text('Open opportunities', 'Oportunidades abiertas')} value={String(summary.open.length)} note={text('excluding won and lost', 'sin ganados ni perdidos')} icon={Users} tone="aqua" /><Metric label={text('Open pipeline value', 'Valor del embudo abierto')} value={money} note={text('estimated midpoint', 'punto medio estimado')} icon={CircleDollarSign} tone="lime" /><Metric label={text('Qualified progression', 'Progreso calificado')} value={`${summary.qualifiedRate.toFixed(1)}%`} note={text('qualified, proposal or won', 'calificado, propuesta o ganado')} icon={BarChart3} tone="violet" /><Metric label={text('Won opportunities', 'Oportunidades ganadas')} value={String(summary.stageCounts.won)} note={text('created in selected period', 'creadas en el período')} icon={ArrowUpRight} tone="coral" /></section>
    <section className="dashboard-grid"><div className="panel funnel-panel"><PanelHeader title={text('CRM funnel', 'Embudo del CRM')} detail={text('Live opportunity stages', 'Etapas de oportunidades')} action={text('Open pipeline', 'Abrir embudo')} onAction={() => onNavigate('Leads & pipeline')} /><div className="funnel-chart"><div className="chart-axis"><span>{chartMax}</span><span>{Math.ceil(chartMax * .75)}</span><span>{Math.ceil(chartMax * .5)}</span><span>{Math.ceil(chartMax * .25)}</span><span>0</span></div><div className="bars">{stageOrder.map((stage, index) => { const count = summary.stageCounts[stage]; return <div className="bar-column" key={stage}><div className={`bar bar-${index < 2 ? 'aqua' : index < 4 ? 'lime' : 'coral'} ${count === 0 ? 'bar-zero' : ''}`} style={{ height: count === 0 ? '0' : `${Math.max(7, count / chartMax * 85)}%` }}><span>{count}</span></div><small>{stageLabel(stage)}</small></div> })}</div></div><div className="chart-foot"><span><i className="legend-dot aqua" /> {mode === 'live' ? text('Supabase records', 'Registros Supabase') : text('Demo records', 'Registros demo')}</span><strong>{records.length} <small>{text('created in period', 'creados en el período')}</small></strong></div></div><div className="panel activity-panel"><PanelHeader title={text('Recent inquiries', 'Consultas recientes')} detail={rangeLabel} action={text('See all', 'Ver todas')} onAction={() => onNavigate('Leads & pipeline')} /><div className="activity-list">{records.slice(0, 4).map(item => <ActivityRow key={item.id} item={item} text={text} />)}{!records.length && mode !== 'loading' && <div className="overview-empty"><Inbox size={22} /><strong>{text('No inquiries in this scope', 'No hay consultas en este alcance')}</strong></div>}{mode === 'loading' && <div className="overview-empty"><LoaderCircle className="spin" size={22} /><strong>{text('Loading inquiries…', 'Cargando consultas…')}</strong></div>}</div></div></section>
    <section className="dashboard-grid bottom-grid"><div className="panel pipeline-panel"><PanelHeader title={text('Pipeline snapshot', 'Vista del embudo')} detail={text('Current selected scope', 'Alcance seleccionado')} action={text('Open CRM', 'Abrir CRM')} onAction={() => onNavigate('Leads & pipeline')} /><div className="pipeline-columns">{stageOrder.slice(0, 4).map((stage, stageIndex) => { const stageRecords = records.filter(item => item.stage === stage); return <div className="pipeline-column" key={stage}><div className="column-head"><span>{stageLabel(stage)}</span><b>{stageRecords.length}</b></div>{stageRecords.slice(0, 2).map(item => <LeadCard key={item.id} item={item} tone={tones[stageIndex]} />)}</div> })}</div></div><div className="panel integrations-panel"><PanelHeader title={text('Data connections', 'Conexiones de datos')} detail={text('Required for complete analytics', 'Necesarias para analítica completa')} action={text('Manage', 'Gestionar')} onAction={() => onNavigate('Account registry')} /><div className="integration-list"><Integration icon={BarChart3} name="Google Analytics 4" detail={text('Traffic and conversions', 'Tráfico y conversiones')} status={text('Pending', 'Pendiente')} /><Integration icon={CircleDollarSign} name="Google Ads" detail={text('Acquisition costs', 'Costos de adquisición')} status={text('Pending', 'Pendiente')} /><Integration icon={Smartphone} name="Google AdMob" detail={text('App and game revenue', 'Ingresos de apps y juegos')} status={text('Pending', 'Pendiente')} /><Integration icon={Bot} name={text('AI copilot', 'Copiloto IA')} detail={text('Recommendations pending key', 'Recomendaciones pendientes de clave')} status={text('Pending', 'Pendiente')} /><Integration icon={Globe2} name="Netlify" detail={text('Forms and deployments', 'Formularios y despliegues')} status={text('Pending', 'Pendiente')} /></div></div></section>
  </>;
}

function Metric({ icon: Icon, label, value, note, tone }: { icon: typeof Users; label: string; value: string; note: string; tone: string }) { return <article className="metric-card"><div className={`metric-icon icon-${tone}`}><Icon size={18} /></div><div className="metric-label">{label}</div><strong className="metric-value">{value}</strong><div className="metric-change">{note}</div></article>; }
function PanelHeader({ title, detail, action, onAction }: { title: string; detail: string; action: string; onAction: () => void }) { return <div className="panel-header"><div><h2>{title}</h2><span>{detail}</span></div><button className="panel-action" onClick={onAction}>{action} <ArrowUpRight size={13} /></button></div>; }
function ActivityRow({ item, text }: { item: OverviewLead; text: (en: string, es: string) => string }) { return <div className="activity-row"><span className="activity-icon icon-aqua"><MessageSquare size={15} /></span><div><strong>{item.name}</strong><small>{item.service || text('General inquiry', 'Consulta general')} · {item.source || text('Unknown source', 'Fuente desconocida')}</small></div><time>{new Intl.DateTimeFormat(undefined, { month: 'short', day: 'numeric' }).format(new Date(item.created_at))}</time></div>; }
function LeadCard({ item, tone }: { item: OverviewLead; tone: string }) { const initials = item.name.split(/\s+/).slice(0, 2).map(part => part[0]).join('').toUpperCase(); const midpoint = item.estimated_value_min !== null && item.estimated_value_max !== null ? (item.estimated_value_min + item.estimated_value_max) / 2 : item.estimated_value_min ?? item.estimated_value_max; return <div className="lead-card"><div className="lead-top"><span className={`lead-avatar avatar-${tone}`}>{initials}</span></div><strong>{item.name}</strong><small>{item.company || 'Independent'}</small><div className="lead-meta"><span>{item.service || 'General'}</span><b>{midpoint === null ? '—' : new Intl.NumberFormat('en-US', { style: 'currency', currency: 'USD', maximumFractionDigits: 0, notation: 'compact' }).format(midpoint)}</b></div></div>; }
function Integration({ icon: Icon, name, detail, status }: { icon: typeof Database; name: string; detail: string; status: string }) { return <div className="integration-row"><span className="integration-icon icon-coral"><Icon size={15} /></span><div><strong>{name}</strong><small>{detail}</small></div><span className="integration-status"><i className="status-dot dot-coral" />{status}</span></div>; }
