import { ArrowRight, BarChart3, BookOpen, Bot, Boxes, CheckCircle2, Inbox, PlugZap, ShieldCheck, Target } from 'lucide-react';

type Props = { language: 'en' | 'es'; onNavigate: (module: string) => void };

export default function UserGuide({ language, onNavigate }: Props) {
  const es = language === 'es';
  const text = (en: string, spanish: string) => es ? spanish : en;
  const modules = [
    [Inbox, text('Leads & pipeline', 'Prospectos y embudo'), text('Capture inquiries, qualify opportunities, estimate value and move each lead through the sales process.', 'Registra consultas, califica oportunidades, estima su valor y mueve cada prospecto por el proceso comercial.'), 'Leads & pipeline'],
    [Boxes, text('Products & goals', 'Productos y objetivos'), text('Keep every website, application, game and service as a separate marketing and attribution scope.', 'Mantén cada sitio, aplicación, videojuego y servicio como un alcance independiente de marketing y atribución.'), 'Products & goals'],
    [Target, text('Campaigns', 'Campañas'), text('Compare channels, spending and qualified outcomes after advertising connections become active.', 'Compara canales, inversión y resultados calificados cuando se activen las conexiones publicitarias.'), 'Campaigns'],
    [BarChart3, text('Analytics', 'Analítica'), text('Understand traffic, conversion and monetization for one product or the whole workspace.', 'Comprende tráfico, conversión y monetización por producto o para todo el espacio.'), 'Analytics'],
    [Bot, text('AI recommendations', 'Recomendaciones IA'), text('Receive evidence-based suggestions while retaining human approval over every important action.', 'Recibe sugerencias basadas en evidencia conservando aprobación humana para cada acción importante.'), 'AI recommendations'],
    [PlugZap, text('Account registry', 'Registro de cuentas'), text('See which external services are connected without placing passwords or secret tokens in CRM records.', 'Consulta qué servicios están conectados sin guardar contraseñas ni tokens secretos en el CRM.'), 'Account registry'],
  ] as const;

  return <div className="guide-page">
    <section className="guide-hero"><div><p className="eyebrow"><span /> {text('SignalDesk user guide', 'Guía de usuario de SignalDesk')}</p><h2>{text('Turn attention into organized growth.', 'Convierte la atención en crecimiento organizado.')}</h2><p>{text('SignalDesk gives a business one private place to understand its products, inquiries, campaigns, conversations and next best actions.', 'SignalDesk ofrece a una empresa un lugar privado para comprender sus productos, consultas, campañas, conversaciones y próximas acciones.')}</p></div><BookOpen size={46} /></section>
    <section className="guide-section"><div className="guide-section-title"><span>01</span><div><h3>{text('The operating goal', 'El objetivo operativo')}</h3><p>{text('Know which product and channel creates valuable customers, then make the next action clear and measurable.', 'Saber qué producto y canal genera clientes valiosos y convertir la siguiente acción en algo claro y medible.')}</p></div></div><div className="goal-grid"><article><Target size={18} /><strong>{text('Acquire', 'Adquirir')}</strong><span>{text('Turn qualified traffic into inquiries.', 'Convertir tráfico calificado en consultas.')}</span></article><article><Inbox size={18} /><strong>{text('Convert', 'Convertir')}</strong><span>{text('Move every opportunity toward a decision.', 'Mover cada oportunidad hacia una decisión.')}</span></article><article><BarChart3 size={18} /><strong>{text('Measure', 'Medir')}</strong><span>{text('Connect spending and effort to outcomes.', 'Relacionar inversión y esfuerzo con resultados.')}</span></article><article><Bot size={18} /><strong>{text('Improve', 'Mejorar')}</strong><span>{text('Use AI advice with human approval.', 'Usar consejos de IA con aprobación humana.')}</span></article></div></section>
    <section className="guide-section"><div className="guide-section-title"><span>02</span><div><h3>{text('Recommended daily workflow', 'Flujo diario recomendado')}</h3><p>{text('A repeatable routine keeps data useful and prevents opportunities from being forgotten.', 'Una rutina repetible mantiene los datos útiles y evita olvidar oportunidades.')}</p></div></div><ol className="workflow-list"><li><b>1</b><span><strong>{text('Review new inquiries', 'Revisa nuevas consultas')}</strong><small>{text('Confirm contact details, source, service and estimated value.', 'Confirma contacto, fuente, servicio y valor estimado.')}</small></span></li><li><b>2</b><span><strong>{text('Qualify and advance', 'Califica y avanza')}</strong><small>{text('Update the stage after every meaningful customer interaction.', 'Actualiza la etapa después de cada interacción importante.')}</small></span></li><li><b>3</b><span><strong>{text('Check performance', 'Revisa el rendimiento')}</strong><small>{text('Compare products and channels using the selected date range.', 'Compara productos y canales usando el período seleccionado.')}</small></span></li><li><b>4</b><span><strong>{text('Decide the next action', 'Decide la siguiente acción')}</strong><small>{text('Review AI recommendations, evidence and risks before accepting anything.', 'Revisa recomendaciones de IA, evidencia y riesgos antes de aceptar algo.')}</small></span></li></ol></section>
    <section className="guide-section"><div className="guide-section-title"><span>03</span><div><h3>{text('Modules and when to use them', 'Módulos y cuándo usarlos')}</h3><p>{text('Each module answers a different business question.', 'Cada módulo responde una pregunta diferente del negocio.')}</p></div></div><div className="guide-module-grid">{modules.map(([Icon, name, description, destination]) => <article key={destination}><Icon size={18} /><h4>{name}</h4><p>{description}</p><button onClick={() => onNavigate(destination)}>{text('Open module', 'Abrir módulo')} <ArrowRight size={13} /></button></article>)}</div></section>
    <section className="guide-section"><div className="guide-section-title"><span>04</span><div><h3>{text('Data trust and safety', 'Confianza y seguridad de datos')}</h3><p>{text('SignalDesk distinguishes live records from representative demonstrations.', 'SignalDesk diferencia registros reales de demostraciones representativas.')}</p></div></div><div className="safety-list"><p><CheckCircle2 size={16} /> {text('A green live-data banner means changes are persisted to the private workspace.', 'Una franja verde de datos conectados significa que los cambios se guardan en el espacio privado.')}</p><p><ShieldCheck size={16} /> {text('Workspace isolation is enforced by Supabase row-level security.', 'El aislamiento del espacio se aplica mediante seguridad por filas de Supabase.')}</p><p><PlugZap size={16} /> {text('Passwords, API keys and OAuth tokens belong in protected environment secrets, never ordinary CRM fields.', 'Las contraseñas, llaves API y tokens OAuth deben estar en secretos protegidos, nunca en campos normales del CRM.')}</p><p><Bot size={16} /> {text('AI may recommend; people approve campaign, budget and publishing decisions.', 'La IA puede recomendar; las personas aprueban decisiones de campañas, presupuesto y publicación.')}</p></div></section>
  </div>;
}
